name: Build and Push Poller Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'poller/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run lint
        run: cd poller && make lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.seaturtle.pw
          username: ${{ gitea.actor }}
          password: ${{ secrets.ACTIONS_PUSH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./poller
          push: true
          tags: git.seaturtle.pw/cavepedia/cavepediav2-poller:latest
