name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.seaturtle.pw
          username: ${{ gitea.actor }}
          password: ${{ secrets.ACTIONS_PUSH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: git.seaturtle.pw/cavepediav2/cavepediav2-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
